version: "3"

services:
  # backend (Development)
  backend:
    build: 
      context: backend/
      dockerfile: DockerfileDev
    expose: 
      - "1323"
    restart: unless-stopped
    environment: 
      DB_HOST: db
    depends_on: 
      - db
    volumes: 
      - ./backend:/app

  # frontend (Development)
  frontend:
    build: 
      context: frontend/
      dockerfile: DockerfileDev
    expose: 
      - "3000"
    restart: "unless-stopped"
    depends_on: 
      - db
      - backend
    volumes: 
      - ./frontend:/app


  # databases
  db:
    build: 
      context: db/
    expose: 
      - "3306"
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: root

  # Proxy gateaway
  gateway: 
    build:
      context: gateway/
    ports: 
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes: 
      - "./gateway/nginx.conf:/etc/nginx/nginx.conf:ro"


  
